### ISSUE TITLE
Request to install python package textblob

### ISSUE THREAD

**Issue by jmunroe** [2i2c-org/utoronto-image#33]
### Context

Origin: https://2i2c.freshdesk.com/a/tickets/187

> Can you please install the latest version of Python package [textblob](https://pypi.org/project/textblob/) on the U of T JupyterHub?

### Proposal

Add `textblob` to `environment.yml`.  This package is available in [conda-forge](https://github.com/conda-forge/textblob-feedstock) and appear to be fairly stable.

According to the [docs](https://textblob.readthedocs.io/en/dev/install.html#with-conda), there is some necessary "NLTK corpora" that needs to be downloaded as well.  Presumably that is a "run once" kind of thing that could be done when the image is being built. 

### Updates and actions

- [ ] Add package to `environment.yml`
- [ ] Download the NLTK corpora as part of building the image
- [ ] Verify the package works as expected (example [workflow](https://textblob.readthedocs.io/en/dev/classifiers.html) )
- [ ] Close ticket on freshdesk

**Comment by sgibson91** [comment]
I have an example of downloading an NLTK corpora in a binder-like build here https://github.com/sgibson91/mybinder.org-user-survey-nlp/blob/main/.binder/postBuild

**Comment by damianavila** [comment]
@GeorgianaElena is already working on this one accordingly to several PRs opened in the last few hours:

* #34
* #35
* #36

**Comment by damianavila** [comment]
And again... it seems to be a complex addition given the underlying complexity of the image...
